services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 12.18.4
      - key: NODE_ENV
        value: production
      - key: DATABASE_HOST
        fromDatabase:
          name: strapi
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: strapi
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: strapi
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: strapi
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: strapi
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true

databases:
  - name: strapi
    plan: starter
